const GAME_COPY = {
  "zh": {
    "label": "游戏素材",
    "headline": "从游戏录屏，到值得分享的高光。",
    "intro": "用视觉理解寻找画面中的精彩事件，生成可编辑的高光与推广草稿。在同一个工作区调整边界、画幅和文字，再导出成片。",
    "flow": "导入、确认、剪辑，一条连贯的流程。",
    "import": "导入素材",
    "confirm": "确认制作方式",
    "edit": "编辑与导出",
    "importText": "导入本地录屏或 B站、YouTube 链接。先做有界快速识别，暂存可恢复。",
    "confirmText": "自动勾选建议的制作类型；你可以取消、补选或切换分析方式。确认后才开始正式理解与剪辑。",
    "editText": "复看候选，调整完整事件的起止点。推广自动匹配竖屏，手动选择优先；使用六款文字预设，在本机渲染并保存。",
    "subtitle": "字幕分析 · 低成本",
    "subtitleText": "适合访谈、课程和有解说的视频。使用字幕与文字模型；旧配置默认保留此路线，无对白的游戏动作不靠字幕判断。",
    "visual": "视觉分析 · 画面事件",
    "visualText": "适合需要理解动作的录屏。自行配置多模态模型并选择视觉分析；仅配置模型不代表授权调用。",
    "privacy": "剪辑与渲染在本机完成。云端文字分析发送相关字幕/文案；云端视觉分析发送抽样画面及必要文字。由你选择服务商，发布时才上传成片到目标平台。",
    "limits": "结果是需要复看的候选和推广草稿。数量取决于有效事件，最多6段高光；边界、裁切和文字仍需人工检查，不保证广告投放效果。",
    "future": "品牌素材库、动态 CTA 与逐词字幕属于后续迭代，不包含在本页的 1.4 基础能力中。",
    "caseTitle": "实际验证：一段跑酷录屏，多段候选",
    "caseText": "内部 macOS 验证使用约5分48秒的跑酷录屏，产出6段高光和3条推广草稿，并完成编辑、导出与系统保存。推广草稿包含同一事件的文案变体；这是单一样本的流程验证，不是多游戏质量或买量效果证明。",
    "download": "查看稳定版下载",
    "back": "返回首页",
    "cost": "文字、视觉与转写费用取决于你的配置和服务商。智能选择先用本地证据；付费视觉初筛需单独启用。",
    "version": "1.4.0 功能预告 · 正式发布后提供",
    "output": "高光 / 推广草稿",
    "illustration": "流程示意 · 非真实产品截图"
  },
  "en": {
    "label": "Game videos",
    "headline": "Turn gameplay recordings into moments worth sharing.",
    "intro": "Find on-screen events with visual analysis and create editable highlights and promotional drafts. Refine boundaries, framing and text in one workspace, then export.",
    "flow": "Import, confirm, edit. One connected workflow.",
    "import": "Import footage",
    "confirm": "Confirm the approach",
    "edit": "Edit and export",
    "importText": "Import a recording or a Bilibili / YouTube link. Bounded screening comes first; unfinished imports can be resumed.",
    "confirmText": "Suggested output types are preselected. Deselect, add or change the analysis route. Full analysis and editing start only after confirmation.",
    "editText": "Review event boundaries. Promotional drafts default to portrait when settings are automatic; manual choices take priority. Use six text presets, render locally and save.",
    "subtitle": "Subtitle analysis · Lower cost",
    "subtitleText": "For interviews, courses and narrated videos. Uses subtitles and a text model; existing configurations keep this route. It does not identify silent gameplay actions.",
    "visual": "Visual analysis · On-screen events",
    "visualText": "For recordings that need action understanding. Configure a multimodal model and choose visual analysis. Configuration alone does not authorize calls.",
    "privacy": "Editing and rendering run locally. Cloud text analysis sends relevant subtitles/copy; cloud visual analysis sends sampled frames and necessary text. You choose the provider. Finished videos are uploaded to a destination only when publishing.",
    "limits": "Outputs are candidates and promotional drafts for review. Up to six highlights, depending on valid events. Check boundaries, crops and copy; campaign performance is not guaranteed.",
    "future": "A brand asset library, animated CTAs and word-by-word captions are future work, not part of the 1.4 basics described here.",
    "caseTitle": "A real workflow check: one runner recording, multiple candidates",
    "caseText": "An internal macOS check used a roughly 5m48s runner recording, produced six highlights and three promotional drafts, and covered editing, export and saving. Drafts included copy variants of one event. This validates a single workflow sample, not multi-game quality or ad performance.",
    "download": "See stable downloads",
    "back": "Back to home",
    "cost": "Text, vision and transcription costs depend on your setup and provider. Smart selection starts with local evidence; paid visual screening requires separate opt-in.",
    "version": "1.4.0 preview · Available after release",
    "output": "Highlights / Promotional drafts",
    "illustration": "Workflow illustration · Not a product screenshot"
  },
  "ja": {
    "label": "ゲーム動画",
    "headline": "ゲーム録画から、共有したくなる瞬間へ。",
    "intro": "視覚分析で画面上のイベントを見つけ、編集可能なハイライトとプロモーション下書きを作成。同じ画面で範囲・画角・文字を調整して書き出せます。",
    "flow": "取り込み、確認、編集をひとつの流れに。",
    "import": "素材を取り込む",
    "confirm": "制作方法を確認",
    "edit": "編集して書き出す",
    "importText": "ローカル録画またはBilibili・YouTubeリンクを取り込みます。まず範囲を限定した簡易判定を行い、未完了の取り込みは再開できます。",
    "confirmText": "推奨する制作タイプを選択済みで表示。解除・追加・分析方法の変更ができ、確認後に本分析と編集を開始します。",
    "editText": "イベントの始点・終点を確認。自動設定のプロモーションは縦型、手動指定を優先。6種の文字プリセットでローカル出力・保存できます。",
    "subtitle": "字幕分析 · 低コスト",
    "subtitleText": "対談、講座、解説付き動画向け。字幕とテキストモデルを使用し、既存設定はこの方法を維持。無音のゲーム動作は識別しません。",
    "visual": "視覚分析 · 画面イベント",
    "visualText": "動作理解が必要な録画向け。マルチモーダルモデルを設定し、視覚分析を選択します。設定だけでは呼び出しを許可しません。",
    "privacy": "編集・描画はローカル。クラウドのテキスト分析には関連字幕や文案、視覚分析には抽出フレームと必要な文字を送信します。提供元を選べ、完成動画は公開操作時のみ配信先へ送信されます。",
    "limits": "結果は確認が必要な候補と下書きです。有効なイベントに応じて最大6本。範囲・切り抜き・文案を確認してください。広告成果は保証しません。",
    "future": "ブランド素材ライブラリ、動くCTA、単語単位の字幕は今後の予定で、本ページの1.4基本機能には含みません。",
    "caseTitle": "実際の検証：1本のランゲーム録画から複数候補",
    "caseText": "macOS内部検証で約5分48秒の録画から6本のハイライトと3本の宣伝下書きを作成し、編集・出力・保存を確認。下書きには同一イベントの文案違いが含まれます。単一素材の動作検証であり、複数ゲームの品質や広告成果の証明ではありません。",
    "download": "安定版のダウンロード",
    "back": "ホームへ",
    "cost": "テキスト・視覚・文字起こしの費用は設定と提供元によります。自動選択はローカル情報から開始。有料の視覚簡易判定は個別に有効化します。",
    "version": "1.4.0 プレビュー · 正式公開後に提供",
    "output": "ハイライト / 宣伝下書き",
    "illustration": "処理の模式図 · 実際の製品画面ではありません"
  },
  "ko": {
    "label": "게임 영상",
    "headline": "게임 녹화에서 공유하고 싶은 순간으로.",
    "intro": "시각 분석으로 화면 속 이벤트를 찾아 편집 가능한 하이라이트와 홍보 초안을 만듭니다. 한 작업 공간에서 구간, 화면 비율, 문구를 조정하고 내보내세요.",
    "flow": "가져오기, 확인, 편집을 하나의 흐름으로.",
    "import": "소재 가져오기",
    "confirm": "제작 방식 확인",
    "edit": "편집 및 내보내기",
    "importText": "로컬 녹화나 Bilibili·YouTube 링크를 가져옵니다. 제한된 빠른 판별부터 진행하며 미완료 가져오기는 복구할 수 있습니다.",
    "confirmText": "추천 제작 유형이 미리 선택됩니다. 해제·추가하거나 분석 방식을 바꿀 수 있으며 확인 후에만 본 분석과 편집을 시작합니다.",
    "editText": "이벤트의 시작과 끝을 검토하세요. 자동 설정의 홍보 초안은 세로형이며 수동 선택이 우선합니다. 6가지 글자 프리셋으로 로컬 렌더링 및 저장합니다.",
    "subtitle": "자막 분석 · 낮은 비용",
    "subtitleText": "인터뷰, 강의, 해설 영상에 적합합니다. 자막과 텍스트 모델을 사용하며 기존 설정은 이 경로를 유지합니다. 대사 없는 게임 동작은 판별하지 않습니다.",
    "visual": "시각 분석 · 화면 이벤트",
    "visualText": "동작 이해가 필요한 녹화용입니다. 멀티모달 모델을 설정하고 시각 분석을 선택하세요. 설정만으로 호출이 허용되지는 않습니다.",
    "privacy": "편집과 렌더링은 로컬에서 실행됩니다. 클라우드 텍스트 분석은 관련 자막·문구를, 시각 분석은 추출 프레임과 필요한 텍스트를 전송합니다. 제공업체는 사용자가 선택하며 완성 영상은 게시할 때만 대상 플랫폼으로 전송됩니다.",
    "limits": "결과는 검토가 필요한 후보와 홍보 초안입니다. 유효한 이벤트에 따라 최대 6개의 하이라이트를 제공합니다. 구간, 크롭, 문구를 확인해야 하며 광고 성과를 보장하지 않습니다.",
    "future": "브랜드 소재 라이브러리, CTA 애니메이션, 단어별 자막은 추후 기능이며 이 페이지의 1.4 기본 기능에는 포함되지 않습니다.",
    "caseTitle": "실제 검증: 러닝 게임 녹화 하나에서 여러 후보",
    "caseText": "내부 macOS 검증에서 약 5분 48초 녹화로 하이라이트 6개와 홍보 초안 3개를 만들고 편집·내보내기·저장을 확인했습니다. 동일 이벤트의 문구 변형이 포함됩니다. 단일 샘플 흐름 검증이며 여러 게임의 품질이나 광고 성과 증거는 아닙니다.",
    "download": "안정 버전 다운로드",
    "back": "홈으로",
    "cost": "텍스트·시각·전사 비용은 설정과 제공업체에 따라 달라집니다. 스마트 선택은 로컬 정보부터 사용하며 유료 시각 사전 판별은 별도로 활성화해야 합니다.",
    "version": "1.4.0 미리보기 · 정식 출시 후 제공",
    "output": "하이라이트 / 홍보 초안",
    "illustration": "흐름 예시 · 실제 제품 화면이 아닙니다"
  },
  "es": {
    "label": "Vídeos de juegos",
    "headline": "De una partida grabada a momentos que vale la pena compartir.",
    "intro": "Encuentra eventos visuales y crea destacados y borradores promocionales editables. Ajusta los cortes, el encuadre y el texto en un mismo espacio y exporta.",
    "flow": "Importar, confirmar y editar. Un solo flujo.",
    "import": "Importa el material",
    "confirm": "Confirma el método",
    "edit": "Edita y exporta",
    "importText": "Importa una grabación local o un enlace de Bilibili o YouTube. Primero se realiza una evaluación limitada; puedes retomar una importación pendiente.",
    "confirmText": "Los tipos de salida sugeridos aparecen seleccionados. Puedes quitarlos, añadirlos o cambiar el análisis. El análisis completo y la edición empiezan tras confirmar.",
    "editText": "Revisa los límites del evento. Los borradores promocionales usan formato vertical en automático; manda tu elección manual. Aplica seis estilos de texto, renderiza localmente y guarda.",
    "subtitle": "Análisis de subtítulos · Menor coste",
    "subtitleText": "Para entrevistas, cursos y vídeos narrados. Usa subtítulos y un modelo de texto; las configuraciones existentes mantienen esta opción. No reconoce acciones de juego sin diálogo.",
    "visual": "Análisis visual · Eventos en pantalla",
    "visualText": "Para grabaciones que requieren comprender acciones. Configura un modelo multimodal y elige análisis visual. Configurarlo no autoriza llamadas.",
    "privacy": "La edición y el renderizado son locales. El análisis de texto en la nube envía subtítulos o textos pertinentes; el visual envía fotogramas seleccionados y texto necesario. Tú eliges el proveedor. El vídeo terminado se sube al destino solo al publicar.",
    "limits": "Los resultados son candidatos y borradores para revisar. Hasta seis destacados según los eventos válidos. Comprueba cortes, encuadre y texto; no se garantizan resultados publicitarios.",
    "future": "La biblioteca de marca, los CTA animados y los subtítulos palabra a palabra quedan para más adelante; no forman parte de estas funciones básicas de 1.4.",
    "caseTitle": "Prueba real: una grabación de carreras, varios candidatos",
    "caseText": "Una prueba interna en macOS con unos 5 min 48 s produjo seis destacados y tres borradores, con edición, exportación y guardado. Incluyen variantes de texto de un mismo evento. Es una prueba de flujo con una muestra, no evidencia de calidad multijuego ni de rendimiento publicitario.",
    "download": "Ver descargas estables",
    "back": "Volver al inicio",
    "cost": "Los costes de texto, visión y transcripción dependen del proveedor y la configuración. La selección inteligente empieza con información local; la evaluación visual de pago requiere activación aparte.",
    "version": "Avance de 1.4.0 · Disponible tras el lanzamiento",
    "output": "Destacados / Borradores promocionales",
    "illustration": "Esquema del flujo · No es una captura del producto"
  },
  "pt": {
    "label": "Vídeos de jogos",
    "headline": "Da gravação de uma partida a momentos que merecem ser compartilhados.",
    "intro": "Encontre eventos visuais e crie destaques e rascunhos promocionais editáveis. Ajuste cortes, enquadramento e texto no mesmo espaço e exporte.",
    "flow": "Importar, confirmar e editar. Um fluxo contínuo.",
    "import": "Importe o material",
    "confirm": "Confirme o método",
    "edit": "Edite e exporte",
    "importText": "Importe uma gravação local ou link do Bilibili ou YouTube. Primeiro ocorre uma avaliação limitada; importações pendentes podem ser retomadas.",
    "confirmText": "Os tipos de saída sugeridos vêm selecionados. Remova, adicione ou altere a análise. A análise completa e a edição começam apenas após a confirmação.",
    "editText": "Revise o início e o fim do evento. Rascunhos promocionais automáticos usam formato vertical; a escolha manual tem prioridade. Use seis estilos de texto, renderize localmente e salve.",
    "subtitle": "Análise de legendas · Menor custo",
    "subtitleText": "Para entrevistas, cursos e vídeos narrados. Usa legendas e modelo de texto; configurações existentes mantêm essa opção. Não identifica ações de jogos sem diálogo.",
    "visual": "Análise visual · Eventos na tela",
    "visualText": "Para gravações que exigem compreensão de ações. Configure um modelo multimodal e selecione análise visual. Configurar não autoriza chamadas.",
    "privacy": "Edição e renderização são locais. A análise de texto na nuvem envia legendas ou textos relevantes; a visual envia quadros selecionados e texto necessário. Você escolhe o provedor. O vídeo final só é enviado ao destino ao publicar.",
    "limits": "Os resultados são candidatos e rascunhos para revisão. Até seis destaques conforme os eventos válidos. Confira cortes, enquadramento e texto; não há garantia de resultado publicitário.",
    "future": "Biblioteca de marca, CTAs animados e legendas palavra por palavra ficam para depois; não fazem parte destas funções básicas de 1.4.",
    "caseTitle": "Teste real: uma gravação de corrida, vários candidatos",
    "caseText": "Um teste interno no macOS com cerca de 5min48s gerou seis destaques e três rascunhos, com edição, exportação e salvamento. Incluem variações de texto do mesmo evento. É um teste de fluxo com uma amostra, não uma prova de qualidade em vários jogos ou de desempenho em anúncios.",
    "download": "Ver downloads estáveis",
    "back": "Voltar ao início",
    "cost": "Custos de texto, visão e transcrição dependem da configuração e do provedor. A seleção inteligente começa com dados locais; a avaliação visual paga exige ativação separada.",
    "version": "Prévia de 1.4.0 · Disponível após o lançamento",
    "output": "Destaques / Rascunhos promocionais",
    "illustration": "Esquema do fluxo · Não é uma captura do produto"
  },
  "ru": {
    "label": "Игровые видео",
    "headline": "Из записи игры — в моменты, которыми хочется поделиться.",
    "intro": "Находите события на экране с помощью визуального анализа и создавайте редактируемые моменты и рекламные черновики. Уточняйте границы, кадрирование и текст в одном рабочем пространстве.",
    "flow": "Импорт, подтверждение, монтаж — единый процесс.",
    "import": "Импорт материала",
    "confirm": "Подтверждение способа",
    "edit": "Монтаж и экспорт",
    "importText": "Импортируйте запись или ссылку Bilibili / YouTube. Сначала выполняется ограниченная предварительная оценка; незавершённый импорт можно продолжить.",
    "confirmText": "Рекомендуемые типы результата уже отмечены. Их можно убрать, добавить или сменить способ анализа. Полный анализ и монтаж начинаются после подтверждения.",
    "editText": "Проверьте начало и конец события. Автоматические рекламные черновики — вертикальные; ручной выбор важнее. Шесть стилей текста, локальный рендеринг и сохранение.",
    "subtitle": "Анализ субтитров · Ниже стоимость",
    "subtitleText": "Для интервью, курсов и видео с комментариями. Использует субтитры и текстовую модель; старые настройки сохраняют этот путь. Действия без речи не распознаются.",
    "visual": "Визуальный анализ · События на экране",
    "visualText": "Для записей, где важно понять действия. Настройте мультимодальную модель и выберите визуальный анализ. Одна настройка не разрешает вызовы.",
    "privacy": "Монтаж и рендеринг выполняются локально. Облачный текстовый анализ получает нужные субтитры и тексты, визуальный — выбранные кадры и необходимый текст. Провайдера выбираете вы. Готовое видео отправляется на площадку только при публикации.",
    "limits": "Результат — кандидаты и черновики для проверки. До шести моментов в зависимости от событий. Проверьте границы, кадрирование и текст; рекламный результат не гарантируется.",
    "future": "Библиотека бренда, анимированные CTA и пословные субтитры запланированы позже и не входят в эти базовые функции 1.4.",
    "caseTitle": "Реальная проверка: одна запись раннера, несколько кандидатов",
    "caseText": "Внутренняя проверка macOS на записи около 5 мин 48 с дала шесть моментов и три черновика с монтажом, экспортом и сохранением. Есть варианты текста одного события. Это проверка процесса на одном примере, а не качества разных игр или эффективности рекламы.",
    "download": "Стабильные загрузки",
    "back": "На главную",
    "cost": "Стоимость текста, изображений и транскрипции зависит от настроек и провайдера. Умный выбор начинает с локальных данных; платная визуальная оценка включается отдельно.",
    "version": "Предпросмотр 1.4.0 · После выпуска",
    "output": "Моменты / Рекламные черновики",
    "illustration": "Схема процесса · Не снимок приложения"
  },
  "fr": {
    "label": "Vidéos de jeux",
    "headline": "De vos parties enregistrées aux moments à partager.",
    "intro": "Repérez les événements à l’écran avec l’analyse visuelle et créez des moments forts et des brouillons promotionnels modifiables. Ajustez les coupes, le cadrage et le texte dans un même espace.",
    "flow": "Importer, confirmer, monter. Un seul parcours.",
    "import": "Importer la vidéo",
    "confirm": "Confirmer la méthode",
    "edit": "Monter et exporter",
    "importText": "Importez une vidéo locale ou un lien Bilibili / YouTube. Une évaluation limitée vient en premier ; une importation en attente peut être reprise.",
    "confirmText": "Les types de sortie suggérés sont présélectionnés. Retirez-en, ajoutez-en ou changez de méthode. L’analyse complète et le montage commencent après confirmation.",
    "editText": "Vérifiez les limites des événements. Les brouillons promotionnels automatiques sont verticaux ; le choix manuel prime. Six styles de texte, rendu local et enregistrement.",
    "subtitle": "Analyse des sous-titres · Coût réduit",
    "subtitleText": "Pour entretiens, cours et vidéos commentées. Utilise sous-titres et modèle texte ; les réglages existants conservent cette méthode. Ne reconnaît pas les actions sans dialogue.",
    "visual": "Analyse visuelle · Événements à l’écran",
    "visualText": "Pour comprendre les actions des vidéos. Configurez un modèle multimodal et choisissez l’analyse visuelle. La configuration seule n’autorise pas les appels.",
    "privacy": "Le montage et le rendu sont locaux. L’analyse texte dans le cloud reçoit les sous-titres ou textes utiles ; l’analyse visuelle reçoit des images échantillonnées et le texte nécessaire. Vous choisissez le fournisseur. La vidéo finale est envoyée à la plateforme uniquement à la publication.",
    "limits": "Les résultats sont des candidats et brouillons à vérifier. Jusqu’à six moments selon les événements valides. Vérifiez coupes, cadrage et texte ; les performances publicitaires ne sont pas garanties.",
    "future": "La bibliothèque de marque, les CTA animés et les sous-titres mot à mot sont prévus plus tard, hors de ces fonctions de base de 1.4.",
    "caseTitle": "Vérification réelle : une vidéo de course, plusieurs candidats",
    "caseText": "Un test interne macOS sur environ 5 min 48 s a produit six moments et trois brouillons, puis couvert montage, export et enregistrement. Certains sont des variantes de texte du même événement. Ce test d’un seul exemple ne prouve ni la qualité sur plusieurs jeux ni les performances publicitaires.",
    "download": "Voir les téléchargements stables",
    "back": "Retour à l’accueil",
    "cost": "Les coûts de texte, vision et transcription dépendent de la configuration et du fournisseur. Le choix intelligent commence par les données locales ; l’évaluation visuelle payante nécessite une activation distincte.",
    "version": "Aperçu 1.4.0 · Disponible après publication",
    "output": "Moments forts / Brouillons promotionnels",
    "illustration": "Schéma du parcours · Pas une capture du produit"
  }
};
