const GAME_COPY = {
  "zh": {
    "label": "游戏素材",
    "headline": "把精彩，剪成主角。",
    "intro": "游戏录屏 → 高光片段 → 推广草稿。发现画面中的精彩，留住完整过程。",
    "flow": "三步，让精彩出场。",
    "import": "放入一段录屏",
    "confirm": "选好制作方向",
    "edit": "打磨，然后导出",
    "importText": "本地视频或链接，统一导入。",
    "confirmText": "AI 推荐，你来确认。",
    "editText": "调整边界、画幅与文字，本机出片。",
    "subtitle": "字幕分析",
    "subtitleText": "有解说的内容，用文字模型轻装上阵。",
    "visual": "视觉分析",
    "visualText": "看懂游戏动作，找到画面里的关键事件。",
    "privacy": "剪辑与渲染在本机完成。云端文字分析发送相关字幕/文案；云端视觉分析发送抽样画面及必要文字。由你选择服务商，发布时才上传成片到目标平台。",
    "limits": "结果是需要复看的候选和推广草稿。数量取决于有效事件，最多6段高光；边界、裁切和文字仍需人工检查，不保证广告投放效果。",
    "future": "品牌素材库、动态 CTA 与逐词字幕属于后续迭代，不包含在本页的 1.4 基础能力中。",
    "caseTitle": "一次录屏，不止一个精彩。",
    "caseText": "内部 macOS 验证使用约5分48秒的跑酷录屏，产出6段高光和3条推广草稿，并完成编辑、导出与系统保存。推广草稿包含同一事件的文案变体；这是单一样本的流程验证，不是多游戏质量或买量效果证明。",
    "download": "查看稳定版下载",
    "back": "返回首页",
    "cost": "文字、视觉与转写费用取决于你的配置和服务商。智能选择先用本地证据；付费视觉初筛需单独启用。",
    "version": "1.4.0 功能预告 · 正式发布后提供",
    "output": "高光 / 推广草稿",
    "illustration": "Subway Princess Runner · 基于实际样片的 AI 合成展示，非产品截图",
    "explore": "看看实际案例",
    "choice": "你的模型，你的选择。",
    "sourceLabel": "原始录屏",
    "highlightLabel": "高光候选",
    "draftLabel": "推广草稿",
    "details": "关于样本、费用与隐私",
    "closing": "从你的下一段录屏开始。",
    "eyebrow": "游戏视觉 · 1.4.0 预告",
    "sampleNote": "单个 macOS 测试样本 · 结果因素材而异",
    "nav.how": "怎么工作",
    "nav.why": "为什么",
    "game.label": "游戏素材",
    "nav.features": "新能力",
    "nav.download": "下载",
    "nav.faq": "常见问题",
    "nav.cta": "下载",
    "footer.podcast": "播客切片",
    "footer.course": "课程高光",
    "footer.publish": "发布教程",
    "footer.feature": "发布",
    "footer.cover": "自动封面",
    "footer.releases": "版本",
    "footer.privacy": "隐私政策",
    "footer.copy": "© 2025–2026 AutoClip · MIT 许可"
  },
  "en": {
    "label": "Game videos",
    "headline": "Give great moments the spotlight.",
    "intro": "Gameplay → highlights → promotional drafts. Find the action. Keep the story.",
    "flow": "Three steps. One creative flow.",
    "import": "Bring your footage",
    "confirm": "Choose your direction",
    "edit": "Refine and export",
    "importText": "Import a local video or a link.",
    "confirmText": "AI suggests. You confirm.",
    "editText": "Tune cuts, framing and text. Render locally.",
    "subtitle": "Subtitle analysis",
    "subtitleText": "Use an affordable text model for narrated content.",
    "visual": "Visual analysis",
    "visualText": "Find key events in on-screen gameplay.",
    "privacy": "Editing and rendering run locally. Cloud text analysis sends relevant subtitles/copy; cloud visual analysis sends sampled frames and necessary text. You choose the provider. Finished videos are uploaded to a destination only when publishing.",
    "limits": "Outputs are candidates and promotional drafts for review. Up to six highlights, depending on valid events. Check boundaries, crops and copy; campaign performance is not guaranteed.",
    "future": "A brand asset library, animated CTAs and word-by-word captions are future work, not part of the 1.4 basics described here.",
    "caseTitle": "One recording. More than one moment.",
    "caseText": "An internal macOS check used a roughly 5m48s runner recording, produced six highlights and three promotional drafts, and covered editing, export and saving. Drafts included copy variants of one event. This validates a single workflow sample, not multi-game quality or ad performance.",
    "download": "See stable downloads",
    "back": "Back to home",
    "cost": "Text, vision and transcription costs depend on your setup and provider. Smart selection starts with local evidence; paid visual screening requires separate opt-in.",
    "version": "1.4.0 preview · Available after release",
    "output": "Highlights / Promotional drafts",
    "illustration": "Subway Princess Runner · AI-composed from real example frames · Not a product screenshot",
    "explore": "Explore the example",
    "choice": "Your model. Your choice.",
    "sourceLabel": "Source recording",
    "highlightLabel": "Highlight candidates",
    "draftLabel": "Promotional drafts",
    "details": "Sample details, costs & privacy",
    "closing": "Start with your next recording.",
    "eyebrow": "GAME VISUALS · 1.4.0 PREVIEW",
    "sampleNote": "One macOS test sample · Results vary by footage",
    "nav.how": "How it works",
    "nav.why": "Why",
    "game.label": "Game videos",
    "nav.features": "Features",
    "nav.download": "Download",
    "nav.faq": "FAQ",
    "nav.cta": "Download",
    "footer.podcast": "Podcast clips",
    "footer.course": "Course highlights",
    "footer.publish": "Publish guide",
    "footer.feature": "Publish",
    "footer.cover": "Auto cover",
    "footer.releases": "Releases",
    "footer.privacy": "Privacy",
    "footer.copy": "© 2025–2026 AutoClip · MIT License"
  },
  "ja": {
    "label": "ゲーム動画",
    "headline": "最高の瞬間を、主役に。",
    "intro": "ゲーム録画からハイライト、プロモーション下書きへ。見せたい瞬間と、その流れを残す。",
    "flow": "3ステップで、見どころを形に。",
    "import": "録画を取り込む",
    "confirm": "制作方針を選ぶ",
    "edit": "磨いて書き出す",
    "importText": "ローカル動画もリンクも、同じ入口から。",
    "confirmText": "AI が提案し、あなたが確認。",
    "editText": "区間・画角・文字を調整してローカル出力。",
    "subtitle": "字幕分析",
    "subtitleText": "解説付きの動画を、低コストの文字モデルで。",
    "visual": "視覚分析",
    "visualText": "画面の動きから重要なイベントを探す。",
    "privacy": "編集・描画はローカル。クラウドのテキスト分析には関連字幕や文案、視覚分析には抽出フレームと必要な文字を送信します。提供元を選べ、完成動画は公開操作時のみ配信先へ送信されます。",
    "limits": "結果は確認が必要な候補と下書きです。有効なイベントに応じて最大6本。範囲・切り抜き・文案を確認してください。広告成果は保証しません。",
    "future": "ブランド素材ライブラリ、動くCTA、単語単位の字幕は今後の予定で、本ページの1.4基本機能には含みません。",
    "caseTitle": "ひとつの録画から、いくつもの見どころ。",
    "caseText": "macOS内部検証で約5分48秒の録画から6本のハイライトと3本の宣伝下書きを作成し、編集・出力・保存を確認。下書きには同一イベントの文案違いが含まれます。単一素材の動作検証であり、複数ゲームの品質や広告成果の証明ではありません。",
    "download": "安定版のダウンロード",
    "back": "ホームへ",
    "cost": "テキスト・視覚・文字起こしの費用は設定と提供元によります。自動選択はローカル情報から開始。有料の視覚簡易判定は個別に有効化します。",
    "version": "1.4.0 プレビュー · 正式公開後に提供",
    "output": "ハイライト / 宣伝下書き",
    "illustration": "Subway Princess Runner · 実際のサンプルを基にした AI 合成画像・製品画面ではありません",
    "explore": "実例を見る",
    "choice": "モデルも方法も、あなた次第。",
    "sourceLabel": "元の録画",
    "highlightLabel": "ハイライト候補",
    "draftLabel": "プロモーション下書き",
    "details": "サンプル・費用・プライバシー",
    "closing": "次の録画から始めよう。",
    "eyebrow": "ゲーム視覚分析 · 1.4.0 予告",
    "sampleNote": "macOS での単一テスト例・結果は素材により異なります",
    "nav.how": "仕組み",
    "nav.why": "特徴",
    "game.label": "ゲーム動画",
    "nav.features": "機能",
    "nav.download": "ダウンロード",
    "nav.faq": "FAQ",
    "nav.cta": "ダウンロード",
    "footer.podcast": "ポッドキャスト",
    "footer.course": "講義ハイライト",
    "footer.publish": "公開ガイド",
    "footer.feature": "公開",
    "footer.cover": "自動カバー",
    "footer.releases": "リリース",
    "footer.privacy": "プライバシー",
    "footer.copy": "© 2025–2026 AutoClip · MIT ライセンス"
  },
  "ko": {
    "label": "게임 영상",
    "headline": "멋진 순간을 주인공으로.",
    "intro": "게임 녹화에서 하이라이트와 홍보 초안까지. 액션과 흐름을 함께 담으세요.",
    "flow": "세 단계로 완성하는 순간.",
    "import": "녹화 가져오기",
    "confirm": "제작 방향 선택",
    "edit": "다듬고 내보내기",
    "importText": "로컬 영상이나 링크로 시작하세요.",
    "confirmText": "AI가 추천하고, 사용자가 확인합니다.",
    "editText": "구간·화면·문구를 조정하고 로컬 렌더링.",
    "subtitle": "자막 분석",
    "subtitleText": "해설 영상은 저렴한 텍스트 모델로.",
    "visual": "시각 분석",
    "visualText": "게임 화면 속 핵심 이벤트를 찾습니다.",
    "privacy": "편집과 렌더링은 로컬에서 실행됩니다. 클라우드 텍스트 분석은 관련 자막·문구를, 시각 분석은 추출 프레임과 필요한 텍스트를 전송합니다. 제공업체는 사용자가 선택하며 완성 영상은 게시할 때만 대상 플랫폼으로 전송됩니다.",
    "limits": "결과는 검토가 필요한 후보와 홍보 초안입니다. 유효한 이벤트에 따라 최대 6개의 하이라이트를 제공합니다. 구간, 크롭, 문구를 확인해야 하며 광고 성과를 보장하지 않습니다.",
    "future": "브랜드 소재 라이브러리, CTA 애니메이션, 단어별 자막은 추후 기능이며 이 페이지의 1.4 기본 기능에는 포함되지 않습니다.",
    "caseTitle": "하나의 녹화, 여러 멋진 순간.",
    "caseText": "내부 macOS 검증에서 약 5분 48초 녹화로 하이라이트 6개와 홍보 초안 3개를 만들고 편집·내보내기·저장을 확인했습니다. 동일 이벤트의 문구 변형이 포함됩니다. 단일 샘플 흐름 검증이며 여러 게임의 품질이나 광고 성과 증거는 아닙니다.",
    "download": "안정 버전 다운로드",
    "back": "홈으로",
    "cost": "텍스트·시각·전사 비용은 설정과 제공업체에 따라 달라집니다. 스마트 선택은 로컬 정보부터 사용하며 유료 시각 사전 판별은 별도로 활성화해야 합니다.",
    "version": "1.4.0 미리보기 · 정식 출시 후 제공",
    "output": "하이라이트 / 홍보 초안",
    "illustration": "Subway Princess Runner · 실제 샘플 기반 AI 합성 이미지 · 제품 스크린샷 아님",
    "explore": "실제 사례 보기",
    "choice": "모델도 방식도 직접 선택.",
    "sourceLabel": "원본 녹화",
    "highlightLabel": "하이라이트 후보",
    "draftLabel": "홍보 초안",
    "details": "샘플·비용·개인정보 안내",
    "closing": "다음 녹화로 시작하세요.",
    "eyebrow": "게임 시각 분석 · 1.4.0 미리보기",
    "sampleNote": "macOS 단일 테스트 사례 · 결과는 소재에 따라 다릅니다",
    "nav.how": "작동 방식",
    "nav.why": "특징",
    "game.label": "게임 영상",
    "nav.features": "기능",
    "nav.download": "다운로드",
    "nav.faq": "FAQ",
    "nav.cta": "다운로드",
    "footer.podcast": "팟캐스트",
    "footer.course": "강의 하이라이트",
    "footer.publish": "게시 가이드",
    "footer.feature": "게시",
    "footer.cover": "자동 커버",
    "footer.releases": "릴리스",
    "footer.privacy": "개인정보",
    "footer.copy": "© 2025–2026 AutoClip · MIT 라이선스"
  },
  "es": {
    "label": "Vídeos de juegos",
    "headline": "Dale protagonismo a cada momento.",
    "intro": "Gameplay → momentos destacados → borradores promocionales. Conserva la acción y su contexto.",
    "flow": "Tres pasos. Un solo flujo.",
    "import": "Importa tu vídeo",
    "confirm": "Elige el enfoque",
    "edit": "Ajusta y exporta",
    "importText": "Un vídeo local o un enlace.",
    "confirmText": "La IA propone. Tú confirmas.",
    "editText": "Ajusta cortes, encuadre y texto. Renderiza localmente.",
    "subtitle": "Análisis de subtítulos",
    "subtitleText": "Modelos de texto económicos para vídeos narrados.",
    "visual": "Análisis visual",
    "visualText": "Encuentra eventos clave en la acción del juego.",
    "privacy": "La edición y el renderizado son locales. El análisis de texto en la nube envía subtítulos o textos pertinentes; el visual envía fotogramas seleccionados y texto necesario. Tú eliges el proveedor. El vídeo terminado se sube al destino solo al publicar.",
    "limits": "Los resultados son candidatos y borradores para revisar. Hasta seis destacados según los eventos válidos. Comprueba cortes, encuadre y texto; no se garantizan resultados publicitarios.",
    "future": "La biblioteca de marca, los CTA animados y los subtítulos palabra a palabra quedan para más adelante; no forman parte de estas funciones básicas de 1.4.",
    "caseTitle": "Una grabación. Más de un gran momento.",
    "caseText": "Una prueba interna en macOS con unos 5 min 48 s produjo seis destacados y tres borradores, con edición, exportación y guardado. Incluyen variantes de texto de un mismo evento. Es una prueba de flujo con una muestra, no evidencia de calidad multijuego ni de rendimiento publicitario.",
    "download": "Ver descargas estables",
    "back": "Volver al inicio",
    "cost": "Los costes de texto, visión y transcripción dependen del proveedor y la configuración. La selección inteligente empieza con información local; la evaluación visual de pago requiere activación aparte.",
    "version": "Avance de 1.4.0 · Disponible tras el lanzamiento",
    "output": "Destacados / Borradores promocionales",
    "illustration": "Subway Princess Runner · Composición con IA basada en muestras reales · No es una captura del producto",
    "explore": "Ver el ejemplo",
    "choice": "Tu modelo. Tú eliges.",
    "sourceLabel": "Grabación original",
    "highlightLabel": "Candidatos destacados",
    "draftLabel": "Borradores promocionales",
    "details": "Muestra, costes y privacidad",
    "closing": "Empieza con tu próxima grabación.",
    "eyebrow": "VISIÓN PARA JUEGOS · AVANCE 1.4.0",
    "sampleNote": "Una muestra en macOS · Los resultados varían",
    "nav.how": "Cómo funciona",
    "nav.why": "Ventajas",
    "game.label": "Vídeos de juegos",
    "nav.features": "Funciones",
    "nav.download": "Descargar",
    "nav.faq": "Preguntas frecuentes",
    "nav.cta": "Descargar",
    "footer.podcast": "Pódcast",
    "footer.course": "Curso",
    "footer.publish": "Guía de publicación",
    "footer.feature": "Publicar",
    "footer.cover": "Portada",
    "footer.releases": "Versiones",
    "footer.privacy": "Privacidad",
    "footer.copy": "© 2025–2026 AutoClip · Licencia MIT"
  },
  "pt": {
    "label": "Vídeos de jogos",
    "headline": "Dê destaque aos melhores momentos.",
    "intro": "Gameplay → destaques → rascunhos promocionais. Preserve a ação e o contexto.",
    "flow": "Três passos. Um só fluxo.",
    "import": "Importe seu vídeo",
    "confirm": "Escolha a direção",
    "edit": "Ajuste e exporte",
    "importText": "Um vídeo local ou um link.",
    "confirmText": "A IA sugere. Você confirma.",
    "editText": "Ajuste cortes, enquadramento e texto. Renderize localmente.",
    "subtitle": "Análise de legendas",
    "subtitleText": "Modelos de texto econômicos para conteúdo narrado.",
    "visual": "Análise visual",
    "visualText": "Encontre eventos importantes na ação do jogo.",
    "privacy": "Edição e renderização são locais. A análise de texto na nuvem envia legendas ou textos relevantes; a visual envia quadros selecionados e texto necessário. Você escolhe o provedor. O vídeo final só é enviado ao destino ao publicar.",
    "limits": "Os resultados são candidatos e rascunhos para revisão. Até seis destaques conforme os eventos válidos. Confira cortes, enquadramento e texto; não há garantia de resultado publicitário.",
    "future": "Biblioteca de marca, CTAs animados e legendas palavra por palavra ficam para depois; não fazem parte destas funções básicas de 1.4.",
    "caseTitle": "Uma gravação. Vários momentos.",
    "caseText": "Um teste interno no macOS com cerca de 5min48s gerou seis destaques e três rascunhos, com edição, exportação e salvamento. Incluem variações de texto do mesmo evento. É um teste de fluxo com uma amostra, não uma prova de qualidade em vários jogos ou de desempenho em anúncios.",
    "download": "Ver downloads estáveis",
    "back": "Voltar ao início",
    "cost": "Custos de texto, visão e transcrição dependem da configuração e do provedor. A seleção inteligente começa com dados locais; a avaliação visual paga exige ativação separada.",
    "version": "Prévia de 1.4.0 · Disponível após o lançamento",
    "output": "Destaques / Rascunhos promocionais",
    "illustration": "Subway Princess Runner · Composição com IA baseada em amostras reais · Não é uma captura do produto",
    "explore": "Ver o exemplo",
    "choice": "Seu modelo. Sua escolha.",
    "sourceLabel": "Gravação original",
    "highlightLabel": "Candidatos a destaque",
    "draftLabel": "Rascunhos promocionais",
    "details": "Amostra, custos e privacidade",
    "closing": "Comece com sua próxima gravação.",
    "eyebrow": "VISÃO PARA JOGOS · PRÉVIA 1.4.0",
    "sampleNote": "Uma amostra no macOS · Os resultados variam",
    "nav.how": "Como funciona",
    "nav.why": "Vantagens",
    "game.label": "Vídeos de jogos",
    "nav.features": "Recursos",
    "nav.download": "Baixar",
    "nav.faq": "Dúvidas frequentes",
    "nav.cta": "Baixar",
    "footer.podcast": "Podcast",
    "footer.course": "Curso",
    "footer.publish": "Guia de publicação",
    "footer.feature": "Publicar",
    "footer.cover": "Capa",
    "footer.releases": "Versões",
    "footer.privacy": "Privacidade",
    "footer.copy": "© 2025–2026 AutoClip · Licença MIT"
  },
  "ru": {
    "label": "Игровые видео",
    "headline": "Лучшим моментам — главную роль.",
    "intro": "Запись игры → хайлайты → промочерновики. Сохраните действие и его контекст.",
    "flow": "Три шага. Один процесс.",
    "import": "Добавьте запись",
    "confirm": "Выберите подход",
    "edit": "Доработайте и экспортируйте",
    "importText": "Локальное видео или ссылка.",
    "confirmText": "ИИ предлагает. Вы подтверждаете.",
    "editText": "Настройте границы, кадр и текст. Рендеринг локальный.",
    "subtitle": "Анализ субтитров",
    "subtitleText": "Недорогая текстовая модель для видео с речью.",
    "visual": "Визуальный анализ",
    "visualText": "Поиск ключевых событий в игровом действии.",
    "privacy": "Монтаж и рендеринг выполняются локально. Облачный текстовый анализ получает нужные субтитры и тексты, визуальный — выбранные кадры и необходимый текст. Провайдера выбираете вы. Готовое видео отправляется на площадку только при публикации.",
    "limits": "Результат — кандидаты и черновики для проверки. До шести моментов в зависимости от событий. Проверьте границы, кадрирование и текст; рекламный результат не гарантируется.",
    "future": "Библиотека бренда, анимированные CTA и пословные субтитры запланированы позже и не входят в эти базовые функции 1.4.",
    "caseTitle": "Одна запись. Много ярких моментов.",
    "caseText": "Внутренняя проверка macOS на записи около 5 мин 48 с дала шесть моментов и три черновика с монтажом, экспортом и сохранением. Есть варианты текста одного события. Это проверка процесса на одном примере, а не качества разных игр или эффективности рекламы.",
    "download": "Стабильные загрузки",
    "back": "На главную",
    "cost": "Стоимость текста, изображений и транскрипции зависит от настроек и провайдера. Умный выбор начинает с локальных данных; платная визуальная оценка включается отдельно.",
    "version": "Предпросмотр 1.4.0 · После выпуска",
    "output": "Моменты / Рекламные черновики",
    "illustration": "Subway Princess Runner · AI-композиция на основе реальных примеров · Не скриншот продукта",
    "explore": "Смотреть пример",
    "choice": "Ваша модель. Ваш выбор.",
    "sourceLabel": "Исходная запись",
    "highlightLabel": "Кандидаты в хайлайты",
    "draftLabel": "Промочерновики",
    "details": "О примере, расходах и приватности",
    "closing": "Начните со следующей записи.",
    "eyebrow": "ВИЗУАЛЬНЫЙ АНАЛИЗ ИГР · АНОНС 1.4.0",
    "sampleNote": "Один тест на macOS · Результаты зависят от видео",
    "nav.how": "Как это работает",
    "nav.why": "Преимущества",
    "game.label": "Игровые видео",
    "nav.features": "Функции",
    "nav.download": "Скачать",
    "nav.faq": "Вопросы",
    "nav.cta": "Скачать",
    "footer.podcast": "Подкаст",
    "footer.course": "Курс",
    "footer.publish": "Как публиковать",
    "footer.feature": "Публикация",
    "footer.cover": "Обложка",
    "footer.releases": "Версии",
    "footer.privacy": "Конфиденциальность",
    "footer.copy": "© 2025–2026 AutoClip · Лицензия MIT"
  },
  "fr": {
    "label": "Vidéos de jeux",
    "headline": "Vos meilleurs moments, au premier plan.",
    "intro": "Gameplay → temps forts → brouillons promotionnels. Gardez l’action et son contexte.",
    "flow": "Trois étapes. Un seul parcours.",
    "import": "Importez votre vidéo",
    "confirm": "Choisissez la direction",
    "edit": "Affinez et exportez",
    "importText": "Une vidéo locale ou un lien.",
    "confirmText": "L’IA propose. Vous confirmez.",
    "editText": "Ajustez coupes, cadrage et texte. Rendu local.",
    "subtitle": "Analyse des sous-titres",
    "subtitleText": "Un modèle de texte économique pour les vidéos commentées.",
    "visual": "Analyse visuelle",
    "visualText": "Repérez les événements clés dans le jeu.",
    "privacy": "Le montage et le rendu sont locaux. L’analyse texte dans le cloud reçoit les sous-titres ou textes utiles ; l’analyse visuelle reçoit des images échantillonnées et le texte nécessaire. Vous choisissez le fournisseur. La vidéo finale est envoyée à la plateforme uniquement à la publication.",
    "limits": "Les résultats sont des candidats et brouillons à vérifier. Jusqu’à six moments selon les événements valides. Vérifiez coupes, cadrage et texte ; les performances publicitaires ne sont pas garanties.",
    "future": "La bibliothèque de marque, les CTA animés et les sous-titres mot à mot sont prévus plus tard, hors de ces fonctions de base de 1.4.",
    "caseTitle": "Une vidéo. Plusieurs temps forts.",
    "caseText": "Un test interne macOS sur environ 5 min 48 s a produit six moments et trois brouillons, puis couvert montage, export et enregistrement. Certains sont des variantes de texte du même événement. Ce test d’un seul exemple ne prouve ni la qualité sur plusieurs jeux ni les performances publicitaires.",
    "download": "Voir les téléchargements stables",
    "back": "Retour à l’accueil",
    "cost": "Les coûts de texte, vision et transcription dépendent de la configuration et du fournisseur. Le choix intelligent commence par les données locales ; l’évaluation visuelle payante nécessite une activation distincte.",
    "version": "Aperçu 1.4.0 · Disponible après publication",
    "output": "Moments forts / Brouillons promotionnels",
    "illustration": "Subway Princess Runner · Composition IA à partir d’exemples réels · Pas une capture du produit",
    "explore": "Voir l’exemple",
    "choice": "Votre modèle. Votre choix.",
    "sourceLabel": "Vidéo source",
    "highlightLabel": "Temps forts proposés",
    "draftLabel": "Brouillons promotionnels",
    "details": "Exemple, coûts et confidentialité",
    "closing": "Commencez avec votre prochaine vidéo.",
    "eyebrow": "VISION POUR LE JEU · APERÇU 1.4.0",
    "sampleNote": "Un exemple testé sur macOS · Les résultats varient",
    "nav.how": "Fonctionnement",
    "nav.why": "Avantages",
    "game.label": "Vidéos de jeux",
    "nav.features": "Fonctions",
    "nav.download": "Télécharger",
    "nav.faq": "FAQ",
    "nav.cta": "Télécharger",
    "footer.podcast": "Podcast",
    "footer.course": "Cours",
    "footer.publish": "Guide de publication",
    "footer.feature": "Publier",
    "footer.cover": "Couverture",
    "footer.releases": "Versions",
    "footer.privacy": "Confidentialité",
    "footer.copy": "© 2025–2026 AutoClip · Licence MIT"
  }
};
