// Run with PLAYWRIGHT_MODULE set to a local Playwright installation if needed.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');
const base=process.env.SITE_URL||'http://127.0.0.1:8770/';const out=process.env.REVIEW_DIR||'/private/tmp/autoclip-site-review';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({headless:true});const p=await b.newPage({viewport:{width:1440,height:1000}});const errors=[];let mediaRequests=0;p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().endsWith('.mp4'))mediaRequests++;});
await p.goto(base+'?lang=zh',{waitUntil:'networkidle'});assert.equal(mediaRequests,0,'videos must load on demand');
await p.locator('#language-picker').click();await p.locator('.locale-options [data-value="en"]').click();await p.waitForTimeout(200);assert.equal(await p.locator('.result-card').count(),4);assert.match(await p.locator('.hero h1').innerText(),/long videos/);
await p.evaluate(()=>scrollTo(0,350));await p.waitForTimeout(300);const t1=await p.locator('.result-card').first().evaluate(e=>getComputedStyle(e).transform);await p.evaluate(()=>scrollTo(0,800));await p.waitForTimeout(450);const t2=await p.locator('.result-card').first().evaluate(e=>getComputedStyle(e).transform);assert.notEqual(t1,t2);await p.evaluate(()=>scrollTo(0,350));await p.waitForTimeout(450);assert.notEqual(await p.locator('.result-card').first().evaluate(e=>getComputedStyle(e).transform),t2);
const played=[];for(const id of [9,11,8,13]){await p.locator(`[data-clip="${id}"]`).click();await p.waitForFunction(()=>document.querySelector('video').currentTime>.1);await p.locator('video').evaluate(v=>v.currentTime=v.duration/2);await p.waitForFunction(()=>{const v=document.querySelector('video');return !v.seeking&&Math.abs(v.currentTime-v.duration/2)<4;});played.push(id);await p.keyboard.press('Escape');await p.waitForFunction(()=>{const v=document.querySelector('video');return v.paused&&!v.hasAttribute('src');});}
await p.locator('#use-cases').scrollIntoViewIfNeeded();await p.locator('[role=tab]').nth(1).click();assert.match(await p.locator('[role=tabpanel]').innerText(),/Courses/);await p.locator('[role=tab]').nth(1).press('ArrowRight');assert.equal(await p.locator('[role=tab]').nth(2).getAttribute('aria-selected'),'true');
await p.setViewportSize({width:390,height:844});const langs=['zh','en','ja','ko','es','pt','ru','fr'];for(const l of langs){await p.locator('#language-picker').click();await p.locator('.locale-options [data-value="'+l+'"]').click();await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,l+' overflow');assert.equal(await p.locator('.result-card').count(),4);}
await p.locator('.site-menu').click();await p.locator('.nav-group').nth(1).locator('summary').click();assert.equal(await p.locator('.nav-group').nth(1).evaluate(e=>e.open),true);await p.keyboard.press('Escape');assert.equal(await p.locator('.site-menu').getAttribute('aria-expanded'),'false');
await p.emulateMedia({reducedMotion:'reduce',colorScheme:'dark'});await p.evaluate(()=>scrollTo(0,0));await p.waitForTimeout(400);assert.ok((await p.locator('.result-card').evaluateAll(es=>es.map(e=>getComputedStyle(e).opacity))).every(v=>v==='1'));await p.screenshot({path:path.join(out,'mobile-dark.png'),fullPage:true});
for(const route of ['use-cases/podcast/','use-cases/course/','use-cases/gameplay/','features/publish/','features/auto-cover/','guides/publish/']){const response=await p.goto(base+route+'?lang=en',{waitUntil:'networkidle'});assert.equal(response.status(),200);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,route);assert.ok(await p.locator('.nav-group').count()||route==='guides/publish/');if(route==='use-cases/podcast/')assert.match(await p.locator('.nav-right > .btn').innerText(),/Download/);}
await p.emulateMedia({colorScheme:'light',reducedMotion:'reduce'});await p.setViewportSize({width:1440,height:1000});await p.goto(base+'?lang=zh',{waitUntil:'networkidle'});await p.screenshot({path:path.join(out,'homepage-zh.png'),fullPage:true});await p.locator('#language-picker').click();await p.locator('.locale-options [data-value="en"]').click();await p.waitForTimeout(200);await p.screenshot({path:path.join(out,'homepage-en.png'),fullPage:true});await p.goto(base+'use-cases/podcast/?lang=en',{waitUntil:'networkidle'});await p.screenshot({path:path.join(out,'podcast-en.png')});assert.deepEqual(errors,[]);console.log(JSON.stringify({played,languages:langs.length,pages:7,errors,mediaLoadedOnDemand:true,scrollReversible:true}));await b.close();})().catch(e=>{console.error(e);process.exit(1)});
